### ISSUE TITLE
No way to set /p:Configuration=Release when cracking projects

### ISSUE THREAD

**Issue by dsyme** [ionide/proj-info#106]
Some host tooling (e.g. fsdocs, or some IDEs) allow the user to indicate the Configuration etc. for the project editing or documentation generation context, e.g.

    dotnet fsdocs ... /p:Configuration=Release 

I was previously using a hacked up version of Dotnet.Projinfo.  I'll send a pull request to allow these collections of parameters to optionally flow into the project cracking.

**Comment by baronfel** [comment]
Closing as @dsyme fixed this in in #107 and that was released as version 0.52.0.
