### ISSUE TITLE
Set location of vswhere

### ISSUE THREAD

**Issue by nojaf** [ionide/proj-info#141]
**Is your feature request related to a problem? Please describe.**
I'm trying to run `FsAutocomplete` locally on a new device.
So far I've only installed the `dotnet sdk` and no Visual Studio.
`ProjInfo` seems to depend on `vswhere`, which can be installed by [Chocolatey](https://community.chocolatey.org/packages/vswhere).

**Describe the solution you'd like**
Could we check an environment variable to use an alternative location of vswhere.
I currently have it at `C:\ProgramData\chocolatey\bin\vswhere.exe`.

**Describe alternatives you've considered**
Installing VS would also do the trick. I'd like to see how far I can get without it.

**Additional context**
If approved, I would be interested in submitting a PR.

**Comment by baronfel** [comment]
That would be a good enhancement, but I think we also need to be more defensive and not assume that the vswhere file is present at all.

**Comment by nojaf** [comment]
Thanks, I also noticed this appears to be on NuGet as well.
https://www.nuget.org/packages/vswhere/

Would it make sense to take a dependency on this and call it from there? Just thinking out loud here.

**Comment by Krzysztof-Cieslak** [comment]
I definitely think we shouldn't require vswhere at all unless the user is actually trying to use proj-info with legacy fsprojs (and in such case they probably have VS installed)
