### ISSUE TITLE
Different result when cracking before and after project restore.

### ISSUE THREAD

**Issue by nojaf** [ionide/proj-info#149]
**Describe the bug**
I'm not sure this is a bug or it is supposed to work this way, but I'm getting a different result for cracking a project that was restored versus non-restored.

**To Reproduce**
I've created a sample at https://github.com/nojaf/ionide.projinfo.tool-referenced-projects-repro.

**Expected behaviour**
`Project1` has a single reference to `Project2`, both before and after restoring.

```
...
ReferencedProjects =
    [{ RelativePath = "..\Project2\Project2.fsproj"
       ProjectFileName =
        "C:\Users\nojaf\Projects\references-repro\Project2\Project2.fsproj"
       TargetFramework = "net6.0" }]
...
```

**Actual behaviour**
After restoring, `Project3` was added as well:
```
ReferencedProjects =
    [{ RelativePath = "..\Project2\Project2.fsproj"
       ProjectFileName =
        "C:\Users\nojaf\Projects\references-repro\Project2\Project2.fsproj"
       TargetFramework = "net6.0" };
     { RelativePath = "..\Project3\Project3.fsproj"
       ProjectFileName =
        "C:\Users\nojaf\Projects\references-repro\Project3\Project3.fsproj"
       TargetFramework = "net6.0" }]
```

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows
 - dotnet SDK version: 6.0.201
 - mono / .Net Framework version: net6
 - ionide.projinfo.tool:      0.58.2

**Additional context**
If this is indeed a bug and you can provide a pointer, I would be interested to take a look at this.

**Comment by baronfel** [comment]
That doesn't surprise me at all - Restore causes _all sorts_ of state changes, and at the moment at least we treat all of that as outside the bounds of this library.

**Comment by nojaf** [comment]
Alright, that is good enough for me.
Thanks for confirming.
