### ISSUE TITLE
`mapToFSharpProjectOptions` for a dense project graph is very slow

### ISSUE THREAD

**Issue by safesparrow** [ionide/proj-info#155]
**Describe the bug**
I'm trying to create FSharpOptions for projects in this solution:
https://github.com/dotnet/fsharp/blob/main/tests/projects/stress/big/dense/Dense.sln

This code works fine:
```
let loader = WorkspaceLoader.Create(toolsPath, props)
let vs = Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()        
let projects = loader.LoadSln(sln, [], BinaryLogGeneration.Off) |> Seq.toList
```
(I'm actually not sure if I need the vs bit - probably not!)

However this bit is taking a huge amount of memory (20GB+) and taking 10min+:
```
        let fsOptions =
            projects
            |> List.map (fun project -> Path.GetFileNameWithoutExtension(project.ProjectFileName), FCS.mapToFSharpProjectOptions project projects)
```
My guess is there is no caching when generating the options so every one out of the exponential number of paths in the graph is being traversed.

**Expected behaviour**
`mapToFSharpOptions` should not process the same project more than once within the same call.

**Screenshots**
DotTrace view:
<img width="877" alt="image" src="https://user-images.githubusercontent.com/2478401/180611932-72ce261c-43dd-401b-a707-93f9ab392027.png">

**Environment (please complete the following information):**
 - OS: Win11
 - Ionide version: 0.59.1
 - VSCode version: Running https://github.com/safesparrow/fsharp-benchmark-generator
 - dotnet SDK version: 6.0.302

**Comment by baronfel** [comment]
We should definitely address this in some way, thanks for the detailed report!

**Comment by safesparrow** [comment]
Thanks for looking into it @baronfel 👍
QQ: What's the root of such a change into a published (prerelease?) NuGet package?

**Comment by baronfel** [comment]
Later tonight, hopefully.
