### ISSUE TITLE
Missing source files and embedded items compared to `dotnet build --no-dependencies`

### ISSUE THREAD

**Issue by safesparrow** [ionide/proj-info#179]
**Describe the bug**
I want to use the ProjInfo library to generate fsc args from an .fsproj - so that I can then run type-checking/compilation tests using the results.

My problem is that `ProjectLoader.getProjectInfo` doesn't return all the command line args that `dotnet build --no-dependencies` uses when launching `fsc`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use ProjInfo to crack the `FSharp.Compiler.ComponentTests.fsproj` in the F# compiler codebase. I've attached the code I'm using below.
2. See that the result does not include the following options/source files:
```
--embed:..\..\artifacts\obj\FSharp.Compiler.ComponentTests\Debug\net7.0\buildproperties.fs
--embed:..\..\artifacts\obj\FSharp.Compiler.ComponentTests\Debug\net7.0\FSharp.Compiler.ComponentTests.AssemblyInfo.fs
--sourcelink:..\..\artifacts\obj\FSharp.Compiler.ComponentTests\Debug\net7.0\FSharp.Compiler.ComponentTests.sourcelink.json
--keyfile:$PACKAGES$\microsoft.dotnet.arcade.sdk\8.0.0-beta.22552.1\tools\snk/MSFT.snk
--refout:..\..\artifacts\obj\FSharp.Compiler.ComponentTests\Debug\net7.0\refint\FSharp.Compiler.ComponentTests.dll
..\..\artifacts\obj\FSharp.Compiler.ComponentTests\Debug\net7.0\buildproperties.fs
..\..\artifacts\obj\FSharp.Compiler.ComponentTests\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.fs
```

**Expected behaviour**
Options/args that can be used to successfully compile the project - same ones that `dotnet build --no-dependencies` uses.

**Screenshots**
Screenshots showing MSBuild properties used by ProjInfo (right) and `dotnet build --no-dependencies` (left):
<img width="1575" alt="image" src="https://user-images.githubusercontent.com/2478401/202313811-29308383-bbbb-498e-83f9-8aa674631b2e.png">
And FSC task properties:
<img width="1577" alt="image" src="https://user-images.githubusercontent.com/2478401/202313906-cdc600bf-6a2e-4c73-b90c-0eb6560f253d.png">

**Code used to call ProjInfo**
```fsharp
let dir = Path.GetDirectoryName projectFile
let _ = Init.init (DirectoryInfo dir) None
let props = []
ProjectLoader.getProjectInfo projectFile props BinaryLogGeneration.Off
```

`.fsproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <OutputType>exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Ionide.ProjInfo.FCS" Version="0.61.0" />

        <PackageReference Include="Microsoft.Build.Framework" Version="17.4.0" ExcludeAssets="runtime" />
        <PackageReference Include="Microsoft.Build.Locator" Version="1.5.5" />
        <PackageReference Include="Microsoft.Build.Tasks.Core" Version="17.4.0" ExcludeAssets="runtime" />
        <PackageReference Include="Microsoft.Build.Utilities.Core" Version="17.4.0" ExcludeAssets="runtime" />
    </ItemGroup>

</Project>
```

**Environment (please complete the following information):**
 - OS: Windows 11
 - Ionide version: -
 - VSCode version: -
 - dotnet SDK version: 7.0.100
 - mono / .Net Framework version: NET7

**Comment by TheAngryByrd** [comment]
Can you generate a binlog from `dotnet build --no-dependencies`? This would help figure out what Targets/Properties you would want to set when cracking a project.

**Comment by safesparrow** [comment]
Actually I think this can be closed now that https://github.com/ionide/proj-info/pull/183 has been merged.
