### ISSUE TITLE
Minimise FSharp.Core version

### ISSUE THREAD

**Issue by Smaug123** [ionide/proj-info#214]
proj-info currently uses FSharp.Core at a very late version, 8.0.400. Could we instead use the earliest possible version, to maximise compatibility with consumers? (I'd raise the PR myself except I'm waiting for https://github.com/ionide/proj-info/pull/211 to land, because I can never get Paket to work right.)

**Comment by baronfel** [comment]
Done - the libraries that don't have a direct FCS dependency target 6.0 now, the ones that do are in sync with whatever version of FCS they may use.
