### ISSUE TITLE
Fix persistent caching

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/proj-info#92]
Before porting to this repository ProjectSystem layer used to do persistent caching using `obj/fsac.cache` file.
This seems to be broken right now - cache files are always empty.

It's not an as huge problem as before because new project cracking is way faster, but we should bring it back anyway.

**Comment by baronfel** [comment]
I think this is an issue with the json serialization arising from the fact that the `internal` on the [type definition](https://github.com/ionide/proj-info/blob/a972839f7ee015f50e7fac9af56c19402acef5a6/src/Ionide.ProjInfo.ProjectSystem/Project.fs#L9-L15) prevents the default newtonsoft serializer from finding constructors on the type.

**Comment by baronfel** [comment]
Fixed this a while back.
