### ISSUE TITLE
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Locator

### ISSUE THREAD

**Issue by tforkmann** [ionide/proj-info#93]
Hi there,

I tried to init the toolspath for my Analyzer.
Somehow the toolspath can not be found.

![image](https://user-images.githubusercontent.com/4168951/102725013-fd6ab300-4313-11eb-843e-37c35e9849a6.png)

I ran into the following error message:
`Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Locator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9dff12846e04bfbd'. Das System kann die angegebene Datei nicht finden.
File name: 'Microsoft.Build.Locator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9dff12846e04bfbd'
   at Ionide.ProjInfo.Init.init()
   at ExpectoTemplate.main(String[] argv) in C:\Users\tforkmann\Documents\1_Tests\AzureTackle.Analyzer\tests\AzureTackleAnalyzer.Tests\Main.fs:line 10`

Any idea what could be the reason for that?
I also just installed the newest VS build tools. 

**Environment (please complete the following information):**
 - OS: Windows 10
 - Ionide version: 5 preview3
 - dotnet SDK version: 5.0.100

**Comment by Krzysztof-Cieslak** [comment]
Is the code OSS? Can you show me the Paket.deps and Paket.lock files?

**Comment by tforkmann** [comment]
Of cause it is :)
But not working yet ;)
https://github.com/tforkmann/AzureTackle.Analyzer

**Comment by Krzysztof-Cieslak** [comment]
Locator should be marked as `copy_local: false` here https://github.com/tforkmann/AzureTackle.Analyzer/blob/master/paket.dependencies#L25
Any other MsBuild library should, but Locator is actually the one that needs to be deployed with your software. 

Here's how we set up MsBuild deps in FSAC:
https://github.com/fsharp/FsAutoComplete/blob/new-project-system/paket.dependencies

**Comment by tforkmann** [comment]
That worked! Thanks
